version: '3'
services:

  LDAP:
    container_name: testapp-webpdf-wsclient-ldap
    image: testapp/webpdf-wsclient-ldap:latest
    build:
      context: ./ldap
      dockerfile: Dockerfile
      args:
        LDAP_SERVER_ID: ldap-1
    environment:
      - PORT=10389
    ports:
      - "10389:10389"
    tty:
      true
    stdin_open:
      true

  webPDF:
    container_name: testapp-webpdf-wsclient-server
    image: testapp/webpdf-wsclient-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      LDAP:
        condition: service_started
    ports:
      - "8080:8080"
      - "8443:8443"
    tty:
      true
    stdin_open:
      true
