<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://schema.webpdf.de/1.0/soap/pdfa"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://schema.webpdf.de/1.0/soap/pdfa" name="PdfaService">
    <wsp:Policy wsu:Id="PdfaPortBinding_MTOM_Policy">
        <ns1:OptimizedMimeSerialization
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
                wsp:Optional="true"/>
    </wsp:Policy>
    <types>
        <xsd:schema>
            <xsd:import namespace="http://schema.webpdf.de/1.0/soap/pdfa"
                        schemaLocation="http://localhost:8080/webPDF/soap/pdfa?xsd=1"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://schema.webpdf.de/1.0/operation"
                        schemaLocation="http://localhost:8080/webPDF/soap/pdfa?xsd=2"/>
        </xsd:schema>
    </types>
    <message name="execute">
        <part name="parameters" element="tns:execute"/>
    </message>
    <message name="executeResponse">
        <part name="parameters" element="tns:executeResponse"/>
    </message>
    <message name="WebserviceException">
        <part name="fault" element="tns:WebserviceException"/>
    </message>
    <portType name="Pdfa">
        <operation name="execute">
            <input wsam:Action="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/executeRequest" message="tns:execute"/>
            <output wsam:Action="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/executeResponse"
                    message="tns:executeResponse"/>
            <fault message="tns:WebserviceException" name="WebserviceException"
                   wsam:Action="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/execute/Fault/WebserviceException"/>
        </operation>
    </portType>
    <binding name="PdfaPortBinding" type="tns:Pdfa">
        <wsp:PolicyReference URI="#PdfaPortBinding_MTOM_Policy"/>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="execute">
            <soap12:operation soapAction=""/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
            <fault name="WebserviceException">
                <soap12:fault name="WebserviceException" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="PdfaService">
        <port name="PdfaPort" binding="tns:PdfaPortBinding">
            <soap12:address location="http://localhost:8080/webPDF/soap/pdfa"/>
        </port>
    </service>
</definitions>