
package net.webpdf.wsclient.schema.stubs;


import net.webpdf.wsclient.schema.operation.ObjectFactory;
import net.webpdf.wsclient.schema.operation.OperationData;
import org.jetbrains.annotations.NotNull;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "URLConverter", targetNamespace = "http://schema.webpdf.de/1.0/soap/urlconverter")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface URLConverter {

    /**
     * This is the webservice execution method of the urlConverter webservice interface.
     *
     * @param operation The selected operation, configuration and parameterization of the webservice call.
     * @return returns javax.activation.DataHandler The DataHandler of the target file for further handling.
     * @throws WebserviceException Shall be thrown, when calling the webservice failed with an error code.
     */
    @WebMethod
    @RequestWrapper(localName = "execute", targetNamespace = "http://schema.webpdf.de/1.0/soap/urlconverter", className = "net.webpdf.wsclient.webservice.stubs.urlconverter.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://schema.webpdf.de/1.0/soap/urlconverter", className = "net.webpdf.wsclient.webservice.stubs.urlconverter.ExecuteResponse")
    @Action(input = "http://schema.webpdf.de/1.0/soap/urlconverter/URLConverter/executeRequest", output = "http://schema.webpdf.de/1.0/soap/urlconverter/URLConverter/executeResponse", fault = {
        @FaultAction(className = WebserviceException.class, value = "http://schema.webpdf.de/1.0/soap/urlconverter/URLConverter/execute/Fault/WebserviceException")
    })
    @NotNull
    DataHandler execute(
        @WebParam(name = "operation", targetNamespace = "http://schema.webpdf.de/1.0/operation")
        @NotNull
            OperationData operation)
        throws WebserviceException
    ;

}
