
package net.webpdf.wsclient.schema.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "WebserviceException")
public class WebserviceException
    extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private FaultInfo faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public WebserviceException(String message, FaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WebserviceException(String message, FaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: net.webpdf.wsclient.schema.stubs.toolbox.FaultInfo
     */
    public FaultInfo getFaultInfo() {
        return faultInfo;
    }

}
